"""Fourth Migration

Revision ID: b6030f9e832d
Revises: 2d6707c84015
Create Date: 2021-11-15 11:03:30.562127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6030f9e832d'
down_revision = '2d6707c84015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_date'), 'comments', ['date'], unique=False)
    op.create_index(op.f('ix_blogs_date'), 'blogs', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_date'), table_name='blogs')
    op.drop_index(op.f('ix_comments_date'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
